apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-dev
  name: nginx-np-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dev
  type: NodePort
status:
  loadBalancer: {}
