apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-cip
  name: nginx-cip
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-cip
  type: ClusterIP
status:
  loadBalancer: {}
